### ISSUE TITLE
Ingress not working with microk8s

### ISSUE THREAD

**Issue by faik** [robomotionio/robomotion-charts#3]
There seems to be 2 errors causing this

# kubectl logs -f nginx-ingress-microk8s-controller-bd4gk -n ingress

1. Permission related
I1224 05:41:10.070315       7 leaderelection.go:277] failed to renew lease ingress/ingress-controller-leader-public: timed out waiting for the condition
I1224 05:41:10.070800       7 leaderelection.go:242] attempting to acquire leader lease  ingress/ingress-controller-leader-public...

2. ingress-class related
I1224 05:41:01.653785       7 store.go:363] ignoring add for ingress robomotion-api based on annotation kubernetes.io/ingress.class with value 
I1224 05:41:01.655069       7 store.go:363] ignoring add for ingress robomotion-authorization based on annotation kubernetes.io/ingress.class with value 
I1224 05:41:01.667906       7 store.go:363] ignoring add for ingress robomotion-designer based on annotation kubernetes.io/ingress.class with value 
I1224 05:41:01.673451       7 store.go:363] ignoring add for ingress robomotion-minio based on annotation kubernetes.io/ingress.class with value 
I1224 05:41:01.677937       7 store.go:363] ignoring add for ingress robomotion-admin based on annotation kubernetes.io/ingress.class with value 
I1224 05:41:01.683763       7 store.go:363] ignoring add for ingress robomotion-proxy based on annotation kubernetes.io/ingress.class with value

**Comment by faik** [comment]
First issue is related to this bug report https://github.com/ubuntu/microk8s/issues/1829

# kubectl -n ingress edit role nginx-ingress-microk8s-role

Replace the resourceNames from ingress-controller-leader-nginx to ngress-controller-leader-public

The second issue is related to ingress class, again it is changed from nginx to public with latest microk8s

# kubectl edit ingress robomotion-proxy

and change kubernetes.io/ingress.class: nginx -> kubernetes.io/ingress.class: public

seems to work.

This should be fixed in robomotion-charts

**Comment by faik** [comment]
Fixed with https://github.com/ubuntu/microk8s/commit/83f24a689c57b1c729c72cf0d4d6df82906e8be6

and 

robomotion-charts commit 990594ecc6e601fa64d3f3dd0e65b3816cb4825d

**Comment by shanebowyer** [comment]
@faik you are a life saver.
This is all I needed to fix my issue

and change kubernetes.io/ingress.class: nginx -> kubernetes.io/ingress.class: public

Thank you
